let fodmaps = [
  "Agave",
  "Almond meal",
  "Amaranth flour",
  "Apples",
  "Apricots",
  "Artichoke",
  "Asparagus",
  "Avocado",
  "Baked beans",
  "Bananas, ripe",
  "Barley including flour",
  "Beer – if drinking more than one bottle",
  "Beetroot, fresh",
  "Biscuits",
  "Black beans",
  "Black eyed peas",
  "Black tea with added soy milk",
  "Blackberries",
  "Blackcurrants",
  "Boysenberry",
  "Bran cereals",
  "Bread",
  "Bread, wheat – over 1 slice",
  "Breadcrumbs",
  "Broad beans",
  "Butter beans",
  "Buttermilk",
  "Cakes",
  "Carob powder",
  "Cashews",
  "Cassava",
  "Cauliflower",
  "Caviar dip",
  "Celery – greater than 5cm of stalk",
  "Cereal bar, wheat based",
  "Chai tea, strong",
  "Chamomile tea",
  "Cheese, Halmoumi",
  "Cheese, cream",
  "Cheese, ricotta",
  "Cherries",
  "Choko",
  "Chorizo",
  "Coconut water",
  "Cordial, apple and raspberry with 50-100% real juice",
  "Cordial, orange with 25-50% real juice",
  "Cous cous",
  "Cow milk",
  "Cream",
  "Croissants",
  "Crumpets",
  "Currants",
  "Custard",
  "Custard apple",
  "Dandelion tea, strong",
  "Dates",
  "Egg noodles",
  "Einkorn flour",
  "Evaporated milk",
  "Falafel",
  "Feijoa",
  "Fennel tea",
  "Fermented cabbage e.g. sauerkraut",
  "Figs",
  "Freekeh",
  "Fructose",
  "Fruit and herbal teas with apple added",
  "Fruit bar",
  "Fruit juices in large quantities",
  "Fruit juices made of apple, pear, mango",
  "Garlic",
  "Gelato",
  "Gnocchi",
  "Goat milk",
  "Goji berries",
  "Granary bread",
  "Granola bar",
  "Grapefruit",
  "Gravy, if it contains onion",
  "Guava, unripe",
  "Haricot beans",
  "Herbal tea, strong",
  "High fructose corn syrup (HFCS)",
  "Honey",
  "Hummus / houmous",
  "Ice cream",
  "Inulin",
  "Isomalt",
  "Jam, mixed berries",
  "Jam, strawberry, if contains HFCS",
  "Kefir",
  "Kidney beans",
  "Kombucha",
  "Leek bulb",
  "Lima beans",
  "Lychee",
  "Malted chocolate flavored drink",
  "Maltitol",
  "Mange Tout",
  "Mango",
  "Mannitol",
  "Milk",
  "Mixed vegetables",
  "Molasses",
  "Muesli bar",
  "Muesli cereal",
  "Muffins",
  "Multigrain bread",
  "Mung beans",
  "Mushrooms",
  "Naan",
  "Nectarines",
  "Oatmeal bread",
  "Onions",
  "Oolong tea",
  "Orange juice in quantities over 100ml",
  "Pasta, wheat over 1/2 cup cooked",
  "Pastries",
  "Paw paw, dried",
  "Peaches",
  "Pears",
  "Peas, sugar snap",
  "Persimmon",
  "Pesto sauce",
  "Pickled vegetables",
  "Pineapple, dried",
  "Pistachios",
  "Plums",
  "Pomegranate",
  "Prunes",
  "Pumpernickel bread",
  "Quince paste",
  "Quinoa milk",
  "Raisins",
  "Red kidney beans",
  "Relish / vegetable pickle",
  "Roti",
  "Rum",
  "Rye",
  "Rye crispbread",
  "Sausages",
  "Savoy Cabbage",
  "Scallions / spring onions (bulb / white part)",
  "Sea buckthorns",
  "Semolina",
  "Shallots",
  "Sheep’s milk",
  "Sodas containing High Fructose Corn Syrup (HFCS)",
  "Sorbitol",
  "Sour cream",
  "Sourdough with kamut",
  "Soy beans / soya beans",
  "Soy milk made with soy beans – commonly found in USA",
  "Spelt flour",
  "Split peas",
  "Sports drinks",
  "Stock cubes",
  "Sugar free sweets containing polyols – usually ending in -ol or isomalt",
  "Sultanas",
  "Tahini paste",
  "Tamarillo",
  "Taro",
  "Tinned fruit in apple / pear juice",
  "Tzatziki dip",
  "Udon noodles",
  "Watermelon",
  "Wheat",
  "Wheat bran",
  "Wheat cereals",
  "Wheat flour",
  "Wheat noodles",
  "Wheat rolls",
  "Wheatgerm",
  "Whey protein, concentrate unless lactose free",
  "Whey protein, hydrolyzed unless lactose free",
  "Wine – if drinking more than one glass",
  "Xylitol",
  "Yoghurt"
];

function findMatches(wordToMatch, fodmaps) {
  return fodmaps.filter(food => {
    // here we need to figure out if the fodmaps matches what was searched
    const regex = new RegExp(wordToMatch, 'gi');
    return food.match(regex);
  });
}

function numberWithCommas(x) {
  return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

function displayMatches() {
  const matchArray = findMatches(this.value, fodmaps);
  const html = matchArray.map(food => {
    const regex = new RegExp(this.value, 'gi');
    const foodHTML = food.replace(regex, `<span class="hl">${this.value}</span>`);
    return `
      <li>
        <span class="name">${foodHTML}</span>
      </li>
    `;
  }).join('');
  suggestions.innerHTML = html;
}

const searchInput = document.querySelector('.search');
const suggestions = document.querySelector('.suggestions');

searchInput.addEventListener('change', displayMatches);
searchInput.addEventListener('keyup', displayMatches);
