let fodmaps = [
  "Garlic",
  "Onions",
  "Artichoke",
  "Asparagus",
  "Baked beans",
  "Bananas, ripe",
  "Beetroot, fresh",
  "Black beans",
  "Black eyed peas",
  "Broad beans",
  "Butter beans",
  "Cassava",
  "Cauliflower",
  "Celery – greater than 5cm of stalk",
  "Choko",
  "Falafel",
  "Fermented cabbage e.g. sauerkraut",
  "Haricot beans",
  "Kidney beans",
  "Lima beans",
  "Leek bulb",
  "Mange Tout",
  "Mixed vegetables",
  "Mung beans",
  "Mushrooms",
  "Peas, sugar snap",
  "Pickled vegetables",
  "Red kidney beans",
  "Savoy Cabbage",
  "Soy beans / soya beans",
  "Split peas",
  "Scallions / spring onions (bulb / white part)",
  "Shallots",
  "Taro",
  "Apples",
  "Apricots",
  "Avocado",
  "Blackberries",
  "Blackcurrants",
  "Boysenberry",
  "Cherries",
  "Currants",
  "Custard apple",
  "Dates",
  "Feijoa",
  "Figs",
  "Goji berries",
  "Grapefruit",
  "Guava, unripe",
  "Lychee",
  "Mango",
  "Nectarines",
  "Paw paw, dried",
  "Peaches",
  "Pears",
  "Persimmon",
  "Pineapple, dried",
  "Plums",
  "Pomegranate",
  "Prunes",
  "Raisins",
  "Sea buckthorns",
  "Sultanas",
  "Tamarillo",
  "Tinned fruit in apple / pear juice",
  "Watermelon",
  "Chorizo",
  "Sausages",
  "Wheat",
  "Biscuits",
  "Bread, wheat – over 1 slice",
  "Breadcrumbs",
  "Cakes",
  "Cereal bar, wheat based",
  "Croissants",
  "Crumpets",
  "Egg noodles",
  "Muffins",
  "Pastries",
  "Pasta, wheat over 1/2 cup cooked",
  "Udon noodles",
  "Wheat bran",
  "Wheat cereals",
  "Wheat flour",
  "Wheat noodles",
  "Wheat rolls",
  "Wheatgerm",
  "Almond meal",
  "Amaranth flour",
  "Barley including flour",
  "Bran cereals",
  "Bread",
  "Granary bread",
  "Multigrain bread",
  "Naan",
  "Oatmeal bread",
  "Pumpernickel bread",
  "Roti",
  "Sourdough with kamut",
  "Cashews",
  "Cous cous",
  "Einkorn flour",
  "Freekeh",
  "Gnocchi",
  "Granola bar",
  "Muesli cereal",
  "Muesli bar",
  "Pistachios",
  "Rye",
  "Rye crispbread",
  "Semolina",
  "Spelt flour",
  "Agave",
  "Caviar dip",
  "Fructose",
  "Fruit bar",
  "Gravy, if it contains onion",
  "High fructose corn syrup (HFCS)",
  "Hummus / houmous",
  "Honey",
  "Jam, mixed berries",
  "Jam, strawberry, if contains HFCS",
  "Molasses",
  "Pesto sauce",
  "Quince paste",
  "Relish / vegetable pickle",
  "Stock cubes",
  "Sugar free sweets containing polyols – usually ending in -ol or isomalt",
  "Inulin",
  "Isomalt",
  "Maltitol",
  "Mannitol",
  "Sorbitol",
  "Xylitol",
  "Tahini paste",
  "Tzatziki dip",
  "Beer – if drinking more than one bottle",
  "Coconut water",
  "Cordial, apple and raspberry with 50-100% real juice",
  "Cordial, orange with 25-50% real juice",
  "Fruit and herbal teas with apple added",
  "Fruit juices in large quantities",
  "Fruit juices made of apple, pear, mango",
  "Kombucha",
  "Malted chocolate flavored drink",
  "Orange juice in quantities over 100ml",
  "Quinoa milk",
  "Rum",
  "Sodas containing High Fructose Corn Syrup (HFCS)",
  "Soy milk made with soy beans – commonly found in USA",
  "Sports drinks",
  "Black tea with added soy milk",
  "Chai tea, strong",
  "Dandelion tea, strong",
  "Fennel tea",
  "Chamomile tea",
  "Herbal tea, strong",
  "Oolong tea",
  "Wine – if drinking more than one glass",
  "Whey protein, concentrate unless lactose free",
  "Whey protein, hydrolyzed unless lactose free",
  "Buttermilk",
  "Cheese, cream",
  "Cheese, Halmoumi",
  "Cheese, ricotta",
  "Cream",
  "Custard",
  "Gelato",
  "Ice cream",
  "Kefir",
  "Milk",
  "Cow milk",
  "Goat milk",
  "Evaporated milk",
  "Sheep’s milk",
  "Sour cream",
  "Yoghurt",
  "Carob powder"
];

function findMatches(wordToMatch, fodmaps) {
  return fodmaps.filter(food => {
    // here we need to figure out if the fodmaps matches what was searched
    const regex = new RegExp(wordToMatch, 'gi');
    return food.match(regex);
  });
}

function numberWithCommas(x) {
  return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

function displayMatches() {
  const matchArray = findMatches(this.value, fodmaps);
  const html = matchArray.map(food => {
    const regex = new RegExp(this.value, 'gi');
    const foodHTML = food.replace(regex, `<span class="hl">${this.value}</span>`);
    return `
      <li>
        <span class="name">${foodHTML}</span>
      </li>
    `;
  }).join('');
  suggestions.innerHTML = html;
}

const searchInput = document.querySelector('.search');
const suggestions = document.querySelector('.suggestions');

searchInput.addEventListener('change', displayMatches);
searchInput.addEventListener('keyup', displayMatches);
